<?php

/* 
 * This file sets the period names for use in other routines
 * Eventually to be replaced by include file directly from nbbrota
 *  
 */
// prepare lookup for shift number => Shift name
         unset($periods);    // Include this line when copying to config.inc.php
            $periods[] = "Car 2 Days";
            $periods[] = "Car 2 Nights";
            $periods[] = "GNAAS Blood on Board";
            $periods[] = "South Bike Days";
            $periods[] = "South Bike Nights";
            $periods[] = "North Bike Days";
            $periods[] = "North Bike Nights";
            $periods[] = "Spare ~ Do Not Use";
            $periods[] = "Spare ~ Do Not Use";
            $periods[] = "Coordinator Mornings";
            $periods[] = "Coordinator Afternoons";
            $periods[] = "Coordinator Evenings";
            $periods[] = "Coordinator Nights";
